language: python

python:
  - "3.5"

env:
  - DJANGO_VERSION=1.10.4
  global:
    - BUILD_ON_TRAVIS=true

install:
  - pip install -q Django==1.10.4

before_script:
  - python manage.py makemigrations

script:
  - python manage.py migrate -v 3
  - python manage.py test -v 3